version: '2'
services:
  amazon-echo-ha-bridge:
    image: timkinbokeh/amazon-echo-ha-bridge
    network_mode: host
  tv-controls:
    image: timkinbokeh/tv-controls
    network_mode: host
    volumes:
    - ${ps4-creds-path}:/root/.ps4-wake.credentials.json

